### ISSUE TITLE
The Scoop (API) Summary

### ISSUE THREAD

**Issue by ad3429** [A-hu/codecademy-unit3#1]
**Criteria 1: Node.js Project Structure**

- Score Level: 4/4
- Comment(s): complete node.js project with testing suite and package.json

**Criteria 2: Implementation of API Specification and Functionality**

- Score Level: 4/4
- Comment(s): All route paths and functionality are implemented to spec. Good job!

**Criteria 3: Test Case Results (Are all Test Cases Passing?)**

- Score Level: 4/4
- Comment(s): Test cases pass. Nice job!

**Criteria 4: JavaScript Fundamentals and Formatting**

- Score Level: 4/4
- Comment(s): Proper use of language features such as functions, variables, etc and JS code is consistently formatted. 

**Overall Score: 16/16**

**Comment by A-hu** [comment]
Thanks, @ad3429
